// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tevo_service.Entities;

#nullable disable

namespace tevo_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250405135426_CLİENT")]
    partial class CLİENT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tevo_service.Entities.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientId"));

                    b.Property<string>("ClientAdres")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("ClientSurname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("ClientTelNo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
